name: Build latest image

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: Version of SoftEtherVPN
        required: false
  schedule:
    - cron: '0 0 * * 0'

jobs:
  prepare:
    name: Prepare for build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.event.inputs.version || steps.latest_version.outputs.release }}
      is_latest: ${{ !github.event.inputs.version || (github.event.inputs.version == steps.latest_version.outputs.release) }}
      skip: ${{ (github.event_name == 'schedule') && (steps.latest_version.outputs.release == steps.latest_build.outputs.value) }}
    steps:
      - id: latest_version
        name: Get latest version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: SoftEtherVPN/SoftEtherVPN_Stable
      - id: latest_build
        name: '[Schedule] Get latest scheduled build version'
        if: ${{ github.event_name == 'schedule' }}
        uses: aaimio/get-persistent-value@v1
        with:
          key: latest_scheduled_version
          access_token: ${{ secrets.PERSISTENT_VALUE_TOKEN }}
  build:
    name: Build image
    runs-on: ubuntu-latest
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.skip == 'false' }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: kyori/softether-vpn-client
          tags: |
            type=raw,value=${{ needs.prepare.outputs.version }}
            type=raw,enable=${{ needs.prepare.outputs.is_latest }},value=latest
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            "version=${{ needs.prepare.outputs.version }}"
      - name: Update DockerHub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: kyori/softether-vpn-client
          short-description: ${{ github.event.repository.description }}
      - name: '[Schedule] Update latest scheduled build version'
        if: ${{ github.event_name == 'schedule' }}
        uses: aaimio/set-persistent-value@v1
        with:
          key: latest_scheduled_version
          value: ${{ needs.prepare.outputs.version }}
          access_token: ${{ secrets.PERSISTENT_VALUE_TOKEN }}
